language: python
sudo: false
dist: xenial

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-server-dev-9.6

services:
  - postgresql

matrix:
  include:
    # These are quick and often catch errors, so list them first
    - python: 3.8
      env: CHECK_DOCS=1
    - python: 3.8
      env: CHECK_FORMATTING=1
    - python: 3.8
    # As of 2018-07-05, Travis's 3.7 and 3.8 builds only work if you
    # use dist: xenial AND sudo: required
    # See: https://github.com/python-trio/trio/pull/556#issuecomment-402879391
    - python: 3.9
      #dist: xenial
      #sudo: required
    - python: 3.10
    - python: 3.11
    - python: 3.12
    # Currently asyncpg uses deprecated `loop` argument, which cause error
    # due to pytest run in `-W error` mode
    # - python: 3.8-dev
    #   dist: xenial
    #   sudo: required
    - os: osx
      language: generic
      env: MACPYTHON=3.8.18
    - os: osx
      language: generic
      env: MACPYTHON=3.8.18

before_script:
  - which pg_config
  - pg_config --version

script:
  - ci/travis.sh
